# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-27 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EasyditaBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easydita_id', models.CharField(max_length=255, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
