# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='easyditabundle',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='easyditabundle',
            name='time_last_received',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
