# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-03 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('image_file', models.ImageField(upload_to='')),
                ('image_hash', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='html',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='html_hash',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='salesforce_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
