# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publish", "0002_auto_20171215_1920"),
    ]

    operations = [
        migrations.AddField(
            model_name="easyditabundle",
            name="complete_production",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="easyditabundle",
            name="complete_review",
            field=models.BooleanField(default=False),
        ),
    ]
