# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-17 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_auto_20171103_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publish.EasyditaBundle'),
        ),
    ]
