# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_auto_20171227_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kav_id', models.CharField(max_length=18, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='easyditabundle',
            old_name='complete_review',
            new_name='complete_draft',
        ),
        migrations.RenameField(
            model_name='easyditabundle',
            old_name='complete_production',
            new_name='complete_publish',
        ),
        migrations.AddField(
            model_name='article',
            name='easydita_bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='publish.EasyditaBundle'),
        ),
    ]
