# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-13 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0004_article_last_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_new',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='html_new',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='ready_to_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='salesforce_kav_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_new',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_new',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
