# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0005_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='easyditabundle',
            name='complete_draft',
        ),
        migrations.RemoveField(
            model_name='easyditabundle',
            name='complete_publish',
        ),
        migrations.AddField(
            model_name='easyditabundle',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('D', 'Draft'), ('P', 'Published')], default='N', max_length=1),
        ),
    ]
