# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0005_auto_20171213_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='last_updated_by',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
