# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0006_auto_20171214_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='easyditabundle',
            name='last_received',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
