# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publish", "0006_auto_20180125_2332"),
    ]

    operations = [
        migrations.AlterField(
            model_name="easyditabundle",
            name="status",
            field=models.CharField(
                choices=[
                    ("N", "New"),
                    ("D", "Draft"),
                    ("G", "Publishing"),
                    ("P", "Published"),
                ],
                default="N",
                max_length=1,
            ),
        ),
    ]
