# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0007_easyditabundle_last_received'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
