# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0008_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='easyditabundle',
            name='last_received',
        ),
        migrations.RemoveField(
            model_name='easyditabundle',
            name='time_created',
        ),
    ]
