# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0009_auto_20180126_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('N', 'New'), ('A', 'Accepted'), ('R', 'Rejected')], default='N', max_length=1)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='easyditabundle',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('Q', 'Queued'), ('C', 'Processing'), ('D', 'Draft'), ('R', 'Rejected'), ('G', 'Publishing'), ('P', 'Published')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='webhook',
            name='easydita_bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='publish.EasyditaBundle'),
        ),
    ]
