# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publish", "0011_auto_20180131_0126"),
    ]

    operations = [
        migrations.AlterField(
            model_name="easyditabundle",
            name="time_queued",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
