# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0013_auto_20180131_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='draft_preview_url',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
