# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0014_article_draft_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='url_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
