# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0016_auto_20180202_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='easyditabundle',
            name='time_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
