# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publish", "0020_auto_20180214_0045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="easyditabundle",
            name="status",
            field=models.CharField(
                choices=[
                    ("N", "New"),
                    ("Q", "Queued"),
                    ("C", "Processing"),
                    ("D", "Ready for Review"),
                    ("R", "Rejected"),
                    ("G", "Publishing"),
                    ("P", "Published"),
                    ("E", "Error"),
                ],
                default="N",
                max_length=1,
            ),
        ),
    ]
