# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publish", "0021_auto_20180215_0613"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="ka_id",
            field=models.CharField(default="", max_length=18),
            preserve_default=False,
        ),
    ]
