# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publish", "0022_article_ka_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="easyditabundle",
            name="time_published",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
