# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publish", "0024_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[("N", "New"), ("C", "Changed")], default="C", max_length=1
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="status",
            field=models.CharField(
                choices=[("N", "New"), ("C", "Changed")], default="C", max_length=1
            ),
            preserve_default=False,
        ),
    ]
