# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publish", "0026_auto_20180226_2020"),
    ]

    operations = [
        migrations.AddField(
            model_name="bundle",
            name="time_last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
