# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0028_auto_20180305_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='draft_preview_url',
            new_name='preview_url',
        ),
    ]
