# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0029_auto_20180306_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
