# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0030_auto_20180313_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('C', 'Changed'), ('U', 'Unchanged'), ('D', 'Deleted')], max_length=1),
        ),
    ]
