# Generated by Django 2.2.3 on 2019-07-17 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publish", "0033_auto_20190713_1833"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="preview_url",
        ),
    ]
