# Generated by Django 2.2.3 on 2019-07-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publish", "0034_remove_article_preview_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundle",
            name="easydita_id",
            field=models.CharField(max_length=255, unique=False),
        ),
    ]
