# Generated by Django 2.2.3 on 2019-07-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0035_auto_20190720_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='easydita_id',
            field=models.CharField(max_length=255, unique=False),
        ),
    ]
