# Generated by Django 2.2.3 on 2019-07-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publish", "0034_auto_20190718_0335"),
        ("publish", "0035_auto_20190720_0301"),
    ]

    operations = []
