# Generated by Django 2.2.1 on 2019-05-31 07:35

from django.db import migrations, models

# https://code.djangoproject.com/ticket/26993
class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
